version: '3'
services:
  python-app:
    build:
      context: ../ProjetMeteo # Remplacez par le chemin réel
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

